spring.application.name=Student Manager
server.port=8080
# MongoDB location (name resolves because of shared network)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

# DB to use
spring.data.mongodb.database=student

# Auth
spring.data.mongodb.username=admin
spring.data.mongodb.password=1234

# Mind that  this asks the asks the mongo to verify the
# credentials with the admin database where the default will be students
# as credentials will be saved in the admin database
spring.data.mongodb.authentication-database=admin